#!/usr/bin/env python3
"""
从 episode_0/15/25/40/45.hdf5 中提取每条轨迹的初始化参数：
  - qpos_ref_0 : t=0  时刻的关节角（前 7 个关节）
  - qpos_ref_12: t=12 时刻的关节角（前 7 个关节）
  - block_xy   : 物块初始位置（HDF5 中无记录，输出 TODO）

输出格式：可直接粘贴到 pick_and_place.py 的 _TRAJ_CONFIGS 中

用法：python extract_traj_params.py
"""

from pathlib import Path
import h5py
import numpy as np

HDF5_DIR  = Path("/storage/zhijun/real_franka/pick_and_place")
TRAJ_IDS  = [0, 15, 25, 40, 45]
T_REF     = 12.0          # 参考帧时刻（秒）
OUTPUT    = Path(__file__).parent / "traj_params.txt"


def extract(traj_id: int) -> dict:
    path = HDF5_DIR / f"episode_{traj_id}.hdf5"
    with h5py.File(path, "r") as f:
        ts       = f["timestamp"][:]
        joint_pos = f["observations/joint_pos"][:]   # (N, 9)

    qpos_0  = joint_pos[0, :7].tolist()

    t0      = ts[0]
    idx_12  = int(np.argmin(np.abs(ts - (t0 + T_REF))))
    actual  = ts[idx_12] - t0
    qpos_12 = joint_pos[idx_12, :7].tolist()

    return {
        "qpos_ref_0":   qpos_0,
        "qpos_ref_12":  qpos_12,
        "idx_12":       idx_12,
        "actual_t12":   actual,
        "n_frames":     len(ts),
    }


def fmt_list(lst: list) -> str:
    return "[" + ", ".join(f"{v}" for v in lst) + "]"


def main():
    lines = [
        "# auto-generated by extract_traj_params.py",
        "# block_xy 需手动测量后填入",
        "# 粘贴到 pick_and_place.py 的 _TRAJ_CONFIGS",
        "",
        "_TRAJ_CONFIGS = {",
    ]

    for traj_id in TRAJ_IDS:
        d = extract(traj_id)
        print(f"[traj {traj_id:2d}] n_frames={d['n_frames']}, "
              f"t12 frame={d['idx_12']} (actual {d['actual_t12']:.4f}s)")
        lines += [
            f'    "{traj_id}": {{',
            f'        "block_xy":    (TODO, TODO),   # 手动填写',
            f'        "qpos_ref_0":  {fmt_list(d["qpos_ref_0"])},',
            f'        "qpos_ref_12": {fmt_list(d["qpos_ref_12"])},',
            f'    }},',
        ]

    lines.append("}")

    text = "\n".join(lines) + "\n"
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"\n✅ 写入完成: {OUTPUT}")
    print("\n" + text)


if __name__ == "__main__":
    main()
